##DROP TABLE IF exists movement;

CREATE TABLE IF NOT EXISTS `movement` (
    PRIMARY KEY (`UNIX_START`,`UNIX_END`,`START_LOCATION`,`DEST_LOCATION`),
`UNIX_START` INT(10) NOT NULL,
`UNIX_END` INT(10) NOT NULL,
`START_LOCATION` VARCHAR(50) NOT NULL,
`DEST_LOCATION` VARCHAR(50) NOT NULL,
`COUNT` INT NULL
)  ENGINE=InnoDB;

SELECT * FROM MOVEMENT;
select * from movement where count > 1 order by count desc;
SELECT *, substring(COORD, 1, instr(COORD,',')-1) as LONGITUDE, substring(COORD, instr(COORD,',')+1) as LATITUDE FROM movement,coordinates WHERE UNIX_START=1440000000 AND movement.START_LOCATION = coordinates.LOCATION;
SELECT * FROM MOVEMENT, coordinates WHERE movement.START_LOCATION = coordinates.LOCATION and unix_start = 14400000;