DROP TABLE IF exists movement;

CREATE TABLE IF NOT EXISTS `movement` (
    PRIMARY KEY (`UNIX_START`,`UNIX_END`,`START_LOCATION`,`DEST_LOCATION`),
`UNIX_START` INT(10) NOT NULL,
`UNIX_END` INT(10) NOT NULL,
`START_LOCATION` VARCHAR(50) NOT NULL,
`DEST_LOCATION` VARCHAR(50) NOT NULL,
`COUNT` INT NULL
)  ENGINE=InnoDB;

SELECT count(*) FROM MOVEMENT;
select * from movement where count > 1;