DROP TABLE if exists STARHUB;

CREATE TABLE IF NOT EXISTS `STARHUB` (
    PRIMARY KEY (`S_ID`,`UNIX_TIME`),
    `S_ID` VARCHAR(32) NOT NULL,
    `UNIX_TIME` INT(10) NOT NULL,
    `SESSION` INT(1) NOT NULL,
    `LOCATION` VARCHAR(50) NOT NULL
)  ENGINE=InnoDB;

LOAD DATA INFILE 'D:\\\\School Files\\RP School Stuffs\\Y3S1\FYP\\
FinalYearProject\\DATA_FOR_RPMASTER.txt'
INTO TABLE STARHUB FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM STARHUB LIMIT 1000000;